routes/web.php
<?php

use App\Mail\ContactEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\BlogPostsController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\FeatureController;
use App\ImageFileName\ImageManagerHelper;
use \App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');


// PANEL

Route::group(['prefix' => 'panel', 'as' => 'panel', 'middleware' => ['auth']], function () {
    Route::get('', function () {return view('panel.index');});

    Route::group(['prefix' => 'post', 'as' => '.post.'], function () {
        Route::get('create', [BlogPostsController::class, 'create'])->name('create');
        Route::get('edit/list', [BlogPostsController::class, 'listPosts'])->name('editList');
        Route::get('edit/{id}', [BlogPostsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [BlogPostsController::class, 'update'])->name('update');
        Route::post('store', [BlogPostsController::class, 'store'])->name('store');
        Route::delete('remove/{id}', [BlogPostsController::class, 'remove'])->name('remove');
    });


    Route::group(['prefix' => 'product', 'as' => '.product.'], function () {
        Route::get('create', [ProductsController::class, 'create'])->name('create');
        Route::post('store', [ProductsController::class, 'store'])->name('store');
        Route::get('edit/list', [ProductsController::class, 'editlist'])->name('editList');
        Route::get('edit/{id}', [ProductsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductsController::class, 'update'])->name('update');
        Route::delete('remove/{id}', [ProductsController::class, 'remove'])->name('remove');
    });

    Route::group(['prefix' => 'feature', 'as' => '.feature.'], function () {
        Route::get('create', [FeatureController::class, 'create'])->name('create');
        Route::post('store', [FeatureController::class, 'storeFeature'])->name('store');
    });
});

// AUTH
Route::group(['prefix' => 'auth', 'as' => 'auth'], function () {
    Route::group(['middleware' => 'logged_in'], function () {
        Route::get('', function () {return view('auth.index');});

        Route::post('login', [LoginController::class, 'login'])->name('.login');
        Route::post('register', [RegisterController::class, 'register'])->name('.register');
    });

    Route::get('logout', [LoginController::class, 'logout'])->name('.logout');
});

// BLOG
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('', [BlogPostsController::class, 'renderBlog'])->name('blog');
    Route::get('{slug}', [BlogPostsController::class, 'show'])->name('show');

});

//PRODUCTS
Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('list', [ProductsController::class, 'list'])->name('list');
    Route::get('cart', [ProductsController::class, 'cart'])->name('cart');
    Route::post('cart/add/{id}', [ProductsController::class, 'addItemToCart'])->name('addItemToCart');
    Route::post('cart/update/{id}', [ProductsController::class, 'updateCart'])->name('updateCart');
    Route::post('cart/remove/{id}', [ProductsController::class, 'removeItemFromCart'])->name('removeItemFromCart');

    Route::get('preview/{slug}', [ProductsController::class, 'show'])->name('show');
});

//CONTACT
Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
    Route::get('form', [ContactController::class, 'form'])->name('form');
    Route::post('send/email', [ContactController::class, 'sendContactEmail'])->name('sendEmail');

});

Route::get('/emailtest', function () {
    Mail::to('email@email.com')->send(new ContactEmail());

});





Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/contact.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('title')
    Kontakt
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2>Kontakt</h2>
            </div>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if (Session::has('success'))
            <div class="col-12 alert alert-success">
                {!! Session::get('success') !!}
            </div>
        @endif
        <div class="row">
            <div class="col-8 offset-2 my-3 py-3 new-post-form">
                <h4 class="text-center">
                        Witaj!<br>
                </h4>
                <span>
                        Jeżeli potrzebujesz się z nami skontaktować z chęcią Ci pomożemy!<br> Wykorzystaj do tego poniższy formularz!
                </span>
                <hr>
                <form action="{{route('contact.sendEmail')}}" method="POST" id="contact-form">
                    @csrf
                    <div class="form-group">
                        <label for="name"><h5>Podaj imię:</h5></label>
                        <input type="text" name="name" class="form-control col-12" id="name" required>
                    </div>
                    <div class="form-group">
                        <label for="email"><h5>Podaj swój email:</h5></label>
                        <input type="email" name="email" class="form-control col-12" id="email" required>
                    </div>
                    <div class="form-group">
                        <label for="topic"><h5>Tytuł wiadomości / problemu:</h5></label>
                        <input type="text" name="topic" class="form-control col-12" id="topic" required>
                    </div>
                    <div class="form-group">
                        <label for="msgContent"><h5>Treść wiadomości:</h5></label>
                        <textarea type="text" name="msgContent" class="form-control col-12" id="editor"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="checkbox" name="active" value="1" class="form-check-label" id="active">
                        <label for="active"><h5>Czy chcesz kopię wiadomości na swój email?</h5></label>
                    </div>
                    <input type="submit" value="Submit" class="btn btn-success btn-block" class="g-recaptcha"
                           data-sitekey="reCAPTCHA_site_key"
                           data-callback='onSubmit'
                           data-action='submit'>

                </form>
            </div>
        </div>
        </div>
    </div>
    {!! htmlScriptTagJsApi() !!}
@endsection

@section('js')

    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .then( editor => {
                console.log( editor );
            } )
            .catch( error => {
                console.error( error );
            } );
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('title')
    Strona główna
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12" align="center">
            <h1>Witaj na stronie :)</h1>
        </div>
    </div>
    <div class="col-12 text-center my-5">
        <h3>Wciąż pracujemy nad tym...</h3>
        <img src="https://img.icons8.com/ios/50/000000/work-light.png" class="my-3"/>
        <h4>Zachęcamy do skorzystania z opcji dostępnych na pasku nawigacji!</h4>
    </div>

</div>

@endsection