routes/web.php
<?php

use App\Mail\ContactEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\BlogPostsController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\FeatureController;
use App\ImageFileName\ImageManagerHelper;
use \App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');


// PANEL

Route::group(['prefix' => 'panel', 'as' => 'panel', 'middleware' => ['auth']], function () {
    Route::get('', function () {return view('panel.index');});

    Route::group(['prefix' => 'post', 'as' => '.post.'], function () {
        Route::get('create', [BlogPostsController::class, 'create'])->name('create');
        Route::get('edit/list', [BlogPostsController::class, 'listPosts'])->name('editList');
        Route::get('edit/{id}', [BlogPostsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [BlogPostsController::class, 'update'])->name('update');
        Route::post('store', [BlogPostsController::class, 'store'])->name('store');
        Route::delete('remove/{id}', [BlogPostsController::class, 'remove'])->name('remove');
    });


    Route::group(['prefix' => 'product', 'as' => '.product.'], function () {
        Route::get('create', [ProductsController::class, 'create'])->name('create');
        Route::post('store', [ProductsController::class, 'store'])->name('store');
        Route::get('edit/list', [ProductsController::class, 'editlist'])->name('editList');
        Route::get('edit/{id}', [ProductsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductsController::class, 'update'])->name('update');
        Route::delete('remove/{id}', [ProductsController::class, 'remove'])->name('remove');
    });

    Route::group(['prefix' => 'feature', 'as' => '.feature.'], function () {
        Route::get('create', [FeatureController::class, 'create'])->name('create');
        Route::post('store', [FeatureController::class, 'storeFeature'])->name('store');
    });
});

// AUTH
Route::group(['prefix' => 'auth', 'as' => 'auth'], function () {
    Route::group(['middleware' => 'logged_in'], function () {
        Route::get('', function () {return view('auth.index');});

        Route::post('login', [LoginController::class, 'login'])->name('.login');
        Route::post('register', [RegisterController::class, 'register'])->name('.register');
    });

    Route::get('logout', [LoginController::class, 'logout'])->name('.logout');
});

// BLOG
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('', [BlogPostsController::class, 'renderBlog'])->name('blog');
    Route::get('{slug}', [BlogPostsController::class, 'show'])->name('show');

});

//PRODUCTS
Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('list', [ProductsController::class, 'list'])->name('list');
    Route::get('cart', [ProductsController::class, 'cart'])->name('cart');
    Route::post('cart/add/{id}', [ProductsController::class, 'addItemToCart'])->name('addItemToCart');
    Route::post('cart/update/{id}', [ProductsController::class, 'updateCart'])->name('updateCart');
    Route::post('cart/remove/{id}', [ProductsController::class, 'removeItemFromCart'])->name('removeItemFromCart');

    Route::get('preview/{slug}', [ProductsController::class, 'show'])->name('show');
});

//CONTACT
Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
    Route::get('form', [ContactController::class, 'form'])->name('form');
    Route::post('send/email', [ContactController::class, 'sendContactEmail'])->name('sendEmail');

});

Route::get('/emailtest', function () {
    Mail::to('email@email.com')->send(new ContactEmail());

});





Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ProductRequest
 * @property int $id
 * @property string $name
 * @property string $description
 * @property double $price
 * @property integer $quantity
 * @property bool $active
 * @property string $meta_name
 * @property string $meta_description
 * @property string $slug
 * @package App\Models
 */

class Product extends Model
{
    use SoftDeletes;

    protected $table = 'products';

    protected $fillable = [
        'name',
        'description',
        'price',
        'quantity',
        'active',
        'meta_name',
        'meta_description',
        'slug',
    ];

    public function images(): HasMany
    {
            return $this->hasMany(ProductImages::class, 'product_id', 'id');
    }

    public function features(): HasMany
    {
        return $this->hasMany(ProductFeatures::class, 'product_id', 'id');
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use Illuminate\Http\Request;
use App\Models\Feature;
use App\Models\Product;
use App\Services\ProductService;
use Gloudemans\Shoppingcart\Facades\Cart;

class ProductsController extends Controller
{
    private ProductService $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    //Features

    public function create()
    {
        $features = Feature::all();

        return view('panel.product.form', ['features' => $features]);
    }

    //Product

    public function store(ProductRequest $request)
    {
        try {
            $this->productService->store($request);
            return redirect(route('product.list'));

        } catch (\Exception $exception) {
                        dd($exception->getMessage(), $exception->getLine(), $exception->getFile());
            return redirect()->back()->withErrors(['is_error' => 'Błąd']);
        }
    }

    public function list()
    {
        $products = Product::query()
            ->with([
                'images',
                'features.feature',
            ])
            ->where('active', 1)
            ->get();

        return view('product.index', ['products' => $products]);
    }

    public function show(string $slug)
    {
        $product = Product::with(['images', 'features'])->where('slug', $slug)->first();

        if (is_null($product)) {
            return redirect(route('product.list'));
        }

        return view('product.single-product', ['product' => $product]);

    }

    // Update product

    public function remove(int $id)
    {
        Product::query()
            ->with([
                'images',
                'features.feature',
            ])
            ->where('id', $id)
            ->delete();

        return redirect(route('panel.product.editList'));
    }

    public function editList()
    {
        $products = Product::query()
            ->with([
                'images',
                'features.feature',
            ])
            ->get();

        return view('panel.product.list', ['products' => $products]);
    }

    public function edit(int $id)
    {
        $features = Feature::all();
        $product = Product::query()
            ->with([
                'images',
                'features.feature',
            ])
            ->find($id);

        return view('panel.product.form', compact('product', 'features'));
    }

    public function update(ProductRequest $request, int $id)
    {
        try {
            $this->productService->update($request, $id);

            return redirect(route('panel.product.editList'));

        } catch (\Exception $exception) {
            dd($exception->getMessage(), $exception->getLine(), $exception->getFile());
            return redirect()->back()->withErrors(['is_error' => 'Błąd']);
        }

    }
    //Cart
    public function addItemToCart(int $id)
    {
        $product = Product::with(['images', 'features'])->where('id', $id)->first();

        Cart::add([
            'id' => $product->id,
            'name' => $product->name,
            'price' => $product->price,
            'weight' => 1, 'qty' => '1',
            'options' => [
                'image' => $product->images[0]->name,
                'quantity' => $product->quantity,
            ],
        ]);

        return redirect()->back();
    }
    public function updateCart(string $rowId, Request $request)
    {
        $getItem = Cart::get($rowId);

        if ($getItem->options->quantity < $request->quantity) {
            return redirect()->back()->with('error', 'Liczba produktów nie może być większa niż max!');
        }
        Cart::update($rowId, $request->quantity);

        return redirect()->back();
    }
    public function removeItemFromCart(string $rowId)
    {
        Cart::remove($rowId);

        return redirect()->back();
    }

    public function cart()
    {
        $cart = Cart::content()->all();

        return view('product.cart', ['cart' => $cart]);
    }
    public function test():void
    {
        Cart::destroy();
    }


}

resources/views/product/cart.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('title')
    Koszyk
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2>Koszyk</h2><br>
            </div>
            @if (Session::has('error'))
                <div class="col-12 alert alert-danger">
                        {!! Session::get('error') !!}

                </div>
            @endif

            @if(empty($cart))

            <div class="col-12 text-center">
                <h4>
                    Produkty pojawią się po dodaniu ich do koszyka :)
                </h4>
            </div>

            @else

            <table class="table table-striped table-edit-list" >
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Zdjęcie produktu</th>
                    <th scope="col" class="w-50">Przedmiot</th>
                    <th scope="col">Ilość</th>
                    <th scope="col">Cena</th>
                    <th scope="col">Akcje</th>
                </tr>
                </thead>
                <tbody>
                @foreach($cart as $singleItem)
                    <tr>
                        <th scope="row" style="width: 10%;">
                            <img src="{{(asset(\App\Services\ProductService::STORAGE_IMAGES_PATH . $singleItem->options->image))}}" class="img-thumbnail" alt="">
                        </th>
                        <th>{{$singleItem->name}}</th>
                        <th>
                            <form action="{{route('product.updateCart', $singleItem->rowId, $singleItem->options->quantity)}}" method="POST" id="quantity-form{{$singleItem->id}}" class="qty-form" name="qtyform[]">
                                @csrf
                                <input name="quantity" type="number" value="{{$singleItem->qty}}" min="1" max="{{$singleItem->options->quantity}}" class="form-control form-control-sm">szt. <br>
                                (Max: {{$singleItem->options->quantity}})<br>
                            </form>
                        </th>
                        <th>{{$singleItem->price}} zł</th>
                        <th>
                            <form action="{{route('product.removeItemFromCart', $singleItem->rowId)}}" method="POST">
                                @csrf
                                <input type="submit" value="X" class="btn btn-danger">
                            </form>
                        </th>
                    </tr>
                @endforeach

                <tr>
                    <th class="text-right pr-5" colspan="4">W sumie: {{Cart::subtotal()}} zł</th>
                    <th>

                    </th>
                </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>

@endsection

@section('js')
    <script>
        document.querySelectorAll('.qty-form').forEach(item => {
            item.addEventListener('change', (event) => {
               submitForm(item);
            })
        });

        function submitForm(element) {
            document.getElementById(element.id).submit();
        }

/*
 var x = document.getElementsByName("qtyform[]");
                console.log(x);

*/

    </script>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('title')
    Produkty
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-2 border-right">
                <s>Kategorie:</s>
                <h4>W BUDOWIE</h4>
            </div>

            <div class="col-10 product">
                @foreach($products as $product)
                <a href="{{route('product.show', ['slug' => $product->slug])}}">
                <div class="row">
                    <div class="col-3">
                        <img src="{{asset(\App\Services\ProductService::STORAGE_IMAGES_PATH . $product->images->first()->name)}}" class="img-fluid img-product img-thumbnail" alt="">
                    </div>
                    <div class="col-9">
                        <span style="font-size: 1.15rem">{{$product->name}}<br></span>
                        <span>Dostępna ilość: {{$product->quantity}}<br></span>
                        <span class="align-bottom" style="position: absolute;bottom:0;font-size: 1.15rem"><b>{{$product->price}}</b> zł (brutto)<br></span>
                        <form action="{{route('product.addItemToCart', $product->id)}}" method="POST">
                            @csrf
                            <input type="submit" value="Dodaj do koszyka" class="btn btn-success" class="align-right" style="position: absolute;right: 0; bottom: 0" >
                        </form>
                    </div>
                </div>
                </a>
                    <hr>
                @endforeach

            </div>
        </div>
    </div>

@endsection

@section('js')

@endsection

resources/views/product/single-product.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" href="{{asset('css/lightbox.css')}}">

@endsection
@section('title')
    Produkty
@endsection

@section('content')
    <div class="container my-2">
        <a href="{{ url()->previous() }}" style="text-decoration: none; color: black">
            <i class="fas fa-angle-double-left"></i> Powrót
        </a>
    </div>
    <div class="container single-product py-4">
        <div class="row">
            <div class="col-4">
                <div class="row">
                @foreach($product->images as $image)
                    @if($image->order == 0)
                        <div class="col-12">
                            <a href="{{asset(\App\Services\ProductService::STORAGE_IMAGES_PATH . $image->name)}}" data-lightbox="roadtrip">
                                <img src="{{asset(\App\Services\ProductService::STORAGE_IMAGES_PATH . $image->name)}}" class="img-fluid img-thumbnail" alt="">
                            </a>
                        </div>
                    @else
                        <div class="col-4">
                            <a href="{{asset(\App\Services\ProductService::STORAGE_IMAGES_PATH . $image->name)}}" data-lightbox="roadtrip">
                                <img src="{{asset(\App\Services\ProductService::STORAGE_IMAGES_PATH . $image->name)}}" class="img-fluid img-thumbnail" alt="">
                            </a>
                        </div>
                    @endif
                @endforeach
                </div>
            </div>
            <div class="col-8">
                <h4>{{$product->name}}</h4><br>
                <h6>Liczba dostępnych sztuk: {{$product->quantity}}</h6><br>
                <h3>{{$product->price}} zł</h3> <br>
                <form action="{{route('product.addItemToCart', $product->id)}}" method="POST">
                    @csrf
                    <input type="submit" value="Dodaj do koszyka" class="btn btn-success btn-block" >
                </form>
            </div>
        </div>
    </div>
    @if($product->features->first())
    <div class="container single-product mt-3 py-3">
        <div class="row">
            <div class="col-12">
                <h4>Cechy produktu:</h4>
                @foreach($product->features as $feature)
                    <b>{{$feature->feature->name}}:</b> {{$feature->value}} <br>
                @endforeach
            </div>
        </div>
    </div>
    @endif
    <div class="container single-product mt-3 py-3">
        <div class="row">
            <div class="col-12">
                <h4>Opis produktu:</h4><br>
                {!!$product->description!!}<br>
            </div>
        </div>
    </div>


@endsection

@section('js')

    <script src="{{asset('js/lightbox-plus-jquery.js')}}"></script>

@endsection