routes/web.php
<?php

use App\Mail\ContactEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\BlogPostsController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\FeatureController;
use App\ImageFileName\ImageManagerHelper;
use \App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');


// PANEL

Route::group(['prefix' => 'panel', 'as' => 'panel', 'middleware' => ['auth']], function () {
    Route::get('', function () {return view('panel.index');});

    Route::group(['prefix' => 'post', 'as' => '.post.'], function () {
        Route::get('create', [BlogPostsController::class, 'create'])->name('create');
        Route::get('edit/list', [BlogPostsController::class, 'listPosts'])->name('editList');
        Route::get('edit/{id}', [BlogPostsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [BlogPostsController::class, 'update'])->name('update');
        Route::post('store', [BlogPostsController::class, 'store'])->name('store');
        Route::delete('remove/{id}', [BlogPostsController::class, 'remove'])->name('remove');
    });


    Route::group(['prefix' => 'product', 'as' => '.product.'], function () {
        Route::get('create', [ProductsController::class, 'create'])->name('create');
        Route::post('store', [ProductsController::class, 'store'])->name('store');
        Route::get('edit/list', [ProductsController::class, 'editlist'])->name('editList');
        Route::get('edit/{id}', [ProductsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductsController::class, 'update'])->name('update');
        Route::delete('remove/{id}', [ProductsController::class, 'remove'])->name('remove');
    });

    Route::group(['prefix' => 'feature', 'as' => '.feature.'], function () {
        Route::get('create', [FeatureController::class, 'create'])->name('create');
        Route::post('store', [FeatureController::class, 'storeFeature'])->name('store');
    });
});

// AUTH
Route::group(['prefix' => 'auth', 'as' => 'auth'], function () {
    Route::group(['middleware' => 'logged_in'], function () {
        Route::get('', function () {return view('auth.index');});

        Route::post('login', [LoginController::class, 'login'])->name('.login');
        Route::post('register', [RegisterController::class, 'register'])->name('.register');
    });

    Route::get('logout', [LoginController::class, 'logout'])->name('.logout');
});

// BLOG
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('', [BlogPostsController::class, 'renderBlog'])->name('blog');
    Route::get('{slug}', [BlogPostsController::class, 'show'])->name('show');

});

//PRODUCTS
Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('list', [ProductsController::class, 'list'])->name('list');
    Route::get('cart', [ProductsController::class, 'cart'])->name('cart');
    Route::post('cart/add/{id}', [ProductsController::class, 'addItemToCart'])->name('addItemToCart');
    Route::post('cart/update/{id}', [ProductsController::class, 'updateCart'])->name('updateCart');
    Route::post('cart/remove/{id}', [ProductsController::class, 'removeItemFromCart'])->name('removeItemFromCart');

    Route::get('preview/{slug}', [ProductsController::class, 'show'])->name('show');
});

//CONTACT
Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
    Route::get('form', [ContactController::class, 'form'])->name('form');
    Route::post('send/email', [ContactController::class, 'sendContactEmail'])->name('sendEmail');

});

Route::get('/emailtest', function () {
    Mail::to('email@email.com')->send(new ContactEmail());

});





Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/blog/index.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('title')
    Blog
@endsection

@section('content')

   <div class="container">
       <div class="container-macy">
           @foreach($posts as $post)
               <div class="single-post">
               <a href="{{route('blog.show', ['slug' => $post->slug])}}">
                    <img src="{{asset(\App\Services\PostService::STORAGE_IMAGES_PATH . $post->image)}}" alt="" class="img-fluid">
                    <h4 class="p-2 topic">{{$post->topic}}</h4>
                    <p class="p-2 teaser">{{$post->teaser}}</p>
               </a>
               </div>
           @endforeach
       </div>
   </div>

@endsection

@section('js')
    <script src="{{asset('js/macy.js')}}"></script>
    <script>
        const msnry = new Macy({
            container: '.container-macy',
            mobileFirst: true,
            columns: 1,
            breakAt: {
                576: 1,
                720: 2,
                960: 3,
            },
            margin : {
                x: 20,
                y: 20,
            }
        });
    </script>
@endsection

resources/views/blog/post.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" href="{{asset('css/post.css')}}">
    <link rel="stylesheet" href="{{asset('css/lightbox.css')}}">

    <style>
        body {
            background-image: url("{{asset(\App\Services\PostService::STORAGE_IMAGES_PATH . $post->image)}}");
            backdrop-filter: blur(15px);
        }
    </style>

@endsection
@section('title')
    Blog
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12 card p-3 mb-5">
                <h4 class="mb-3">{{$post->topic}}</h4>
                {!!$post->content !!}
                <hr>
                    <a href="{{asset(\App\Services\PostService::STORAGE_IMAGES_PATH . $post->image)}}" rel="lightbox" data-lightbox="image-1" data-title="My caption">
                        <img src="{{asset(\App\Services\PostService::STORAGE_IMAGES_PATH . $post->image)}}" alt="" class="img-fluid py-3 mx-auto d-block photo" id="image-1">
                    </a>
                <hr>
                <span>Autor: {{$post->postAuthor->name}}</span>
                <span>Data dodania: {{$post->created_at}}</span>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script src="{{asset('js/lightbox-plus-jquery.js')}}"></script>

@endsection