routes/web.php
<?php

use App\Mail\ContactEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\BlogPostsController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\FeatureController;
use App\ImageFileName\ImageManagerHelper;
use \App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');


// PANEL

Route::group(['prefix' => 'panel', 'as' => 'panel', 'middleware' => ['auth']], function () {
    Route::get('', function () {return view('panel.index');});

    Route::group(['prefix' => 'post', 'as' => '.post.'], function () {
        Route::get('create', [BlogPostsController::class, 'create'])->name('create');
        Route::get('edit/list', [BlogPostsController::class, 'listPosts'])->name('editList');
        Route::get('edit/{id}', [BlogPostsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [BlogPostsController::class, 'update'])->name('update');
        Route::post('store', [BlogPostsController::class, 'store'])->name('store');
        Route::delete('remove/{id}', [BlogPostsController::class, 'remove'])->name('remove');
    });


    Route::group(['prefix' => 'product', 'as' => '.product.'], function () {
        Route::get('create', [ProductsController::class, 'create'])->name('create');
        Route::post('store', [ProductsController::class, 'store'])->name('store');
        Route::get('edit/list', [ProductsController::class, 'editlist'])->name('editList');
        Route::get('edit/{id}', [ProductsController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductsController::class, 'update'])->name('update');
        Route::delete('remove/{id}', [ProductsController::class, 'remove'])->name('remove');
    });

    Route::group(['prefix' => 'feature', 'as' => '.feature.'], function () {
        Route::get('create', [FeatureController::class, 'create'])->name('create');
        Route::post('store', [FeatureController::class, 'storeFeature'])->name('store');
    });
});

// AUTH
Route::group(['prefix' => 'auth', 'as' => 'auth'], function () {
    Route::group(['middleware' => 'logged_in'], function () {
        Route::get('', function () {return view('auth.index');});

        Route::post('login', [LoginController::class, 'login'])->name('.login');
        Route::post('register', [RegisterController::class, 'register'])->name('.register');
    });

    Route::get('logout', [LoginController::class, 'logout'])->name('.logout');
});

// BLOG
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('', [BlogPostsController::class, 'renderBlog'])->name('blog');
    Route::get('{slug}', [BlogPostsController::class, 'show'])->name('show');

});

//PRODUCTS
Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('list', [ProductsController::class, 'list'])->name('list');
    Route::get('cart', [ProductsController::class, 'cart'])->name('cart');
    Route::post('cart/add/{id}', [ProductsController::class, 'addItemToCart'])->name('addItemToCart');
    Route::post('cart/update/{id}', [ProductsController::class, 'updateCart'])->name('updateCart');
    Route::post('cart/remove/{id}', [ProductsController::class, 'removeItemFromCart'])->name('removeItemFromCart');

    Route::get('preview/{slug}', [ProductsController::class, 'show'])->name('show');
});

//CONTACT
Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
    Route::get('form', [ContactController::class, 'form'])->name('form');
    Route::post('send/email', [ContactController::class, 'sendContactEmail'])->name('sendEmail');

});

Route::get('/emailtest', function () {
    Mail::to('email@email.com')->send(new ContactEmail());

});





Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/app.blade.php
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Aguafina+Script&display=swap" rel="stylesheet">
    @yield('css')

    <title>@yield('title')</title>
</head>
<body>
@include('layouts.navbar')

@yield('content')

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="{{asset('js/ckeditor.js')}}"></script>

@yield('js')
</body>
</html>

resources/views/layouts/navbar.blade.php
<header class="mb-4">
    <nav class="navbar navbar-expand navbar-login-panel my-0">
        <div class="container">
            <button class="navbar-toggler navbar-dark d-block d-md-none" type="button" data-toggle="collapse" data-target="#collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a href="{{route('index')}}" class="navbar-brand navbar-dark d-block d-md-none mx-auto" style="font-family: 'Lobster', cursive;">
                <i class="fas fa-shopping-basket header-logo"></i>
                <span class="header-text">Smart Shop</span>
            </a>
            <ul class="navbar-nav ml-auto list-inline">
                @if(\Illuminate\Support\Facades\Auth::check())
                <li class="nav-item d-inline">
                    <span class="nav-link d-block"><a href="{{route('panel')}}"> Witaj {{\Illuminate\Support\Facades\Auth::user()->name}}</a></span>
                </li>
                <li class="nav-item list-inline-item">
                    <a href="{{route('auth.logout')}}" class="nav-link">
                       Wyloguj się <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
                @else
                <li class="nav-item list-inline-item">
                    <a href="{{route('auth')}}" class="nav-link">
                        Logowanie/Rejestracja <i class="fas fa-sign-in-alt"></i>
                    </a>
                </li>
                @endif
            </ul>
        </div>
    </nav>



    <div class="navbar navbar-expand-md navbar-dark navbar-buttons-panel my-0 py-0 pt-1" id="lower-navbar">
        <div class="container">
            <a href="{{route('index')}}" class="navbar-brand navbar-dark d-none d-md-block" style="font-family: 'Lobster', cursive;">
                <i class="fas fa-shopping-basket header-logo"></i>
                <span class="header-text">Smart Shop</span>
            </a>
            <div class="collapse navbar-collapse" id="collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{{route('index')}}" class="nav-item nav-link navbar-button" title="Strona główna">
                            Strona główna
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-item nav-link navbar-button disabled">
                            <del>Promocje</del>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('product.list')}}" class="nav-item nav-link navbar-button">
                            Sklep
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('blog.blog')}}" class="nav-item nav-link navbar-button">
                            Blog
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('contact.form')}}" class="nav-item nav-link navbar-button" >
                            Kontakt
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('product.cart')}}" class="nav-link">
                            <i class="fas fa-shopping-basket"></i> <sup>({{Cart::count()}})</sup>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>